name: 'YouthSignal ゲーム開発リポジトリ初期化'

on: workflow_dispatch

jobs:
  initialize-gamedev-repository:
    runs-on: ubuntu-latest

    timeout-minutes: 1

    steps:
      - run: cat $GITHUB_EVENT_PATH

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get repository name and description
        run: |
          cat $GITHUB_EVENT_PATH | jq '.repository | .name = "REPO_NAME=" + .name | .description = "REPO_DESCRIPTION=" + .description | .name, .description' | sed -e 's/"//g' >> $GITHUB_ENV

      - name: Update README.md
        run: |
          echo -e "# $REPO_NAME\n\n$REPO_DESCRIPTION" > README.md

      - name: Commit & Push
        run: |
          git config user.name actions-user[bot]
          git config user.email action@github.com
          git add .
          git commit -m 'YouthSignal ゲーム開発リポジトリ初期化'
          git push

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Add team repository permissions
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            orgs/${{ env.REPO_OWNER }}/teams/${{ env.TEAM_NAME }}/repos/${{ env.REPO_OWNER }}/${{ env.REPO_NAME }} \
            -f permission='push'
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          REPO_OWNER: ${{ github.repository_owner }}
          TEAM_NAME: script-directors
